---
- name: Vhost configuration file
  template:
    src: vhosts.conf.j2
    dest: "{{ httpd.server_root }}/conf.d/vhost.conf"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: restart apache
  tags:
    - apache
