# roles/httpd/defaults/main.yml
---
httpd:
   repo: ~
   mods: [mod_ssl]
   server_root: '/etc/httpd'
   document_root_base_dir: /var/www
   listen: 80
   user: apache
   group: apache
   main:
       document_root: 'html'
       server_admin: root@localhost
       server_name: localhost
       server_tokens: Prod
       error_log: logs/error_log
       access_log: logs/access_log
       log_level: warn
   vhost:
       document_root: 'html'
       listen: 80
       server_name: dummy.hk
       server_alias: dummy.hk
       server_admin: root@localhost
       server_tokens: Prod
       error_log: logs/error_log
       access_log: logs/access_log
       log_level: warn

php:
  extensions:
    - php
    - php-common
    - php-pdo
    - php-gd
    - php-opcache
    - php-memcached
    - php-cli
    - php-mysqlnd
    - php-mysqli
    - php-xml
    - php-openssl
    - php-mbstring
    - php-zip
    - php-intl
    - php-posix
    - php-pgsql
