---
- name: Install dnf-plugins.core
  dnf:
    name: dnf-plugins-core
    state: present
  tags:
    - docker

- name: Install repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install docker
  dnf:
    name: 
      - docker-ce
      - docker-compose
    state: present
  tags:
    - docker  
    
- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: true
  tags:
    - docker
